Fix sqlline by removing redundant slf4j dependency (log4j-over-slf4j) from cassandra-all
SLF4J initialization was failing due to `NoClassDefFoundError`.


Former-commit-id: b43a314b60f42d1e58febc39c04cbbbefc3503e1